language: objective-c

branches:
  except:
    - gh-pages

install:
  - gem install xcpretty

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="CodeField"
    - UPDATE_DOCS="true"

matrix:
  include:
  # - osx_image: xcode10.1
  #   env: SCHEME="macOS"  SDK="macosx10.13"      DESTINATION="arch=x86_64"                     SWIFT_VERSION="3.2" ACTION="test"
  # - osx_image: xcode10.1
  #   env: SCHEME="macOS"  SDK="macosx10.14"      DESTINATION="arch=x86_64"                     SWIFT_VERSION="4.1" ACTION="test"
    - osx_image: xcode10.2
      env: SCHEME="iOS"    SDK="iphonesimulator"  DESTINATION="OS=12.2,name=iPhone 8"           SWIFT_VERSION="4.2" ACTION="test"
  # - osx_image: xcode10.1
  #   env: SCHEME="watchOS"  SDK="watchsimulator" DESTINATION="OS=4.0,name=Apple Watch - 42mm"  SWIFT_VERSION="4.2" ACTION="build"
  # - osx_image: xcode10.1
  #   env: SCHEME="tvOS"   SDK="appletvsimulator" DESTINATION="OS=12.0,name=Apple TV 4K"        SWIFT_VERSION="4.0" ACTION="test"

cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild
    -workspace "Example/$FRAMEWORK_NAME.xcworkspace"
    -scheme "$FRAMEWORK_NAME-$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
    GCC_GENERATE_TEST_COVERAGE_FILES=YES
    SWIFT_VERSION=$SWIFT_VERSION
